<<<<<<< HEAD
[server]
maxUploadSize=2
[theme]
base="dark"
primaryColor="#06ff00"
=======
[server]
maxUploadSize=2
[theme]
base="dark"
primaryColor="#06ff00"
>>>>>>> d947d00395e15309a47e06566e1ea92f0b32bd24
